import pytest
from bayora.services.llm_proxy.inference import SandboxedInference
from bayora.services.llm_proxy.bus import LLMProxyBus, LLM_KEY
from cryptography.fernet import Fernet
import gc

from unittest.mock import MagicMock, patch

@pytest.fixture(autouse=True)
def mock_inference_engine():
    with patch.object(SandboxedInference, '_load_model', autospec=True) as mock_load:
        def side_effect(instance):
            instance.llm_engine = None
            instance.model = MagicMock()
            instance.tokenizer = MagicMock()
            # Still load the small embedding model for semantic tests
            from sentence_transformers import SentenceTransformer
            instance.embedding_model = SentenceTransformer('sentence-transformers/all-MiniLM-L6-v2')
        mock_load.side_effect = side_effect
        yield mock_load

def test_inference_echo_filter():
    engine = SandboxedInference()
    prompt = "Hello World"
    # Force an echo for testing
    response = "You said: Hello World. How can I help?"
    
    filtered = engine._apply_sandbox_filters(prompt, response)
    assert "[ECHO_FILTERED]" in filtered
    assert "Hello World" not in filtered

def test_inference_semantic_similarity_filter():
    # Use a high threshold for testing
    engine = SandboxedInference(similarity_threshold=0.6)
    
    # Prompt and a semantically similar response (paraphrase)
    prompt = "The blue team uses a Merkle-chained audit log to ensure forensic integrity."
    response = "Forensic integrity is guaranteed by the blue team through a Merkle-linked audit trail."
    
    filtered = engine._apply_sandbox_filters(prompt, response)
    assert "[SEMANTIC_ECHO_FILTERED]" in filtered
    
    # Non-similar response
    safe_response = "I cannot provide information about the blue team's logic."
    safe_filtered = engine._apply_sandbox_filters(prompt, safe_response)
    assert "[SEMANTIC_ECHO_FILTERED]" not in safe_filtered
    assert "I cannot provide" in safe_filtered

def test_session_isolation_cleanup():
    engine = SandboxedInference()
    assert engine.model is not None
    
    engine.end_session()
    assert engine.model is None
    
def test_llm_proxy_bus_flow():
    engine = SandboxedInference()
    # Mock the infer method to return a predictable response
    engine.infer = MagicMock(return_value="LLM Response")
    bus = LLMProxyBus(engine)
    
    # Simulate a session key generated by session-manager
    session_key = Fernet.generate_key().decode()
    
    # Encrypt prompt with LLM_KEY (as session-manager would)
    llm_fernet = Fernet(LLM_KEY.encode())
    prompt = b"Test prompt"
    encrypted_prompt = llm_fernet.encrypt(prompt)
    
    # Process
    encrypted_resp = bus.process_request(encrypted_prompt, session_key)
    
    # Verify response is encrypted with session_key
    sess_fernet = Fernet(session_key.encode())
    decrypted_resp = sess_fernet.decrypt(encrypted_resp)
    assert b"LLM Response" in decrypted_resp

def test_cross_session_contamination_prevention():
    """
    FR-3: Verify that session 2 cannot access data from session 1.
    """
    engine = SandboxedInference()
    
    # Session 1
    engine.model = "session_1_state"
    engine.end_session()
    assert engine.model is None
    
    # Session 2
    engine.reload()
    assert engine.model is not None
    assert engine.model != "session_1_state"
